# Generated by Django 5.2 on 2025-04-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='user',
        ),
        migrations.AddField(
            model_name='receipt',
            name='image',
            field=models.ImageField(default=0.00014109347442680775, upload_to='receipts/'),
            preserve_default=False,
        ),
    ]
